### ISSUE TITLE
What's the orientation of the 3D point from Rigging.js?

### ISSUE THREAD

**Issue by zhang11wu4** [haruiz/RiggingJs#19]
I get a lot of 3D points form hand keypoints, [x, y, z] , but i dont know what's there orientation, who can tell me? thank you.

**Comment by delebash** [comment]
The hand pose estimation is using the tensorflow javascript code here https://github.com/tensorflow/tfjs-models/tree/master/handpose.  This is the code that is being used in the hand pose estimation.

**Comment by haruiz** [comment]
@zhang11wu4 here it's the code that computes the rotation matrix [computeHeadPoseEstimation](https://github.com/haruiz/RiggingJs/blob/f78d3c80c75a543b8c6c2d09dd7586220fd29e7d/src/util/geometry.util.js#L39), and this method uses that matrix to get the orientation [rotationMatrixToEulerAngles](https://github.com/haruiz/RiggingJs/blob/f78d3c80c75a543b8c6c2d09dd7586220fd29e7d/src/util/geometry.util.js#L111).
